### ISSUE TITLE
TODO For 0.4

### ISSUE THREAD

**Issue by scarlehoff** [scarlehoff/lhapdf_management#1]
0.4 will be a commodity release so that removing `lhapdf` from the `nnpdf` code requires less changes, it will come together with a new releasee of pdfflow with the same reasons

- [x] `--init` option for `update` so that it creates the folder at wherever it should (default `sys.prefix / share / LHAPDF`
- [x] `setVerbosity(int)` option which might not do anything
- [x] `paths()` function that just returns the current datapath
- [x] Put the test in the CI 
- [x] Automatize creating the package.
